[gmail]
source        = imaps://twang9739%40gmail.com:vjdcktoscsxiferv@imap.gmail.com:993
outgoing      = smtps://twang9739%40gmail.com:vjdcktoscsxiferv@smtp.gmail.com:465
default       = INBOX
from          = TylerWayne <twang9739@gmail.com>
cache-headers = true
use-gmail-ext = true

[qqmail]
source        = imaps://twang9739%40qq.com:ahoeapcznovhihad@imap.qq.com:993
outgoing      = smtps://twang9739%40qq.com:ahoeapcznovhihad@smtp.qq.com:465
default       = INBOX
from          = WangTao <twang9739@qq.com>
cache-headers = true
