font_size 12.0

background_opacity 0.8

confirm_os_window_close 0

remember_window_size  no

enable_audio_bell no

# # When using Mono font, symbols are generally smaller
# # symbols use different fonts depending on the code
# symbol_map U+23FB-U+2B58 Symbols Nerd Font Mono
# symbol_map U+E000-U+F553 Symbols Nerd Font Mono
# symbol_map U+F0001-U+F1AF0 Symbols Nerd Font Mono

# # Fix font truncation caused by low DPI, such as g
# modify_font cell_height 2px
# # or
# modify_font cell_height 1.1

# BEGIN_KITTY_THEME
# Tokyo Night Moon
include current-theme.conf
# END_KITTY_THEME


# BEGIN_KITTY_FONTS
font_family      family="CaskaydiaCove Nerd Font"
bold_font        auto
italic_font      auto
bold_italic_font auto
# END_KITTY_FONTS
