conky.config = {
    background = true,
    update_interval = 1,
    double_buffer = true,
    no_buffers = true,
    text_buffer_size = 2048,
    own_window = true,
    own_window_type = 'override',
    own_window_transparent = true,
    own_window_argb_visual = true,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',
    alignment = 'top_right',
    gap_x = 20,
    gap_y = 40,
    use_xft = true,
    default_color = 'white',
    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    draw_graph_borders = false,
};

conky.text = [[
${font DejaVu Sans Mono:bold:size=14}${color1}${alignc}${time %H:%M:%S}
${font Xiaolai Mono SC:size=10}${alignc}${color}${time %A, %d %B %Y}${color}
${font DejaVu Sans Mono:size=10}

Uptime:   $uptime
CPU:      ${cpu}% ${cpubar 5}
RAM:      $mem / $memmax ($memperc%) ${membar 5}
Disk:     ${fs_used /} / ${fs_size /} ${fs_bar 5}
Net ↓↑:   ${downspeed enp3s0} / ${upspeed enp3s0}
]];
