conky.config = {
    background = true,
    update_interval = 1,
    double_buffer = true,
    no_buffers = true,
    text_buffer_size = 2048,
    imlib_cache_size = 0,

	minimum_width= 400,

    own_window = true,
    own_window_type = 'override',
    own_window_transparent = false,
    own_window_argb_visual = true,
    own_window_argb_value = 120,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

    alignment = 'top_right',
    gap_x = 20,
    gap_y = 50,

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    draw_graph_borders = true,

    use_xft = true,
    font = 'DejaVu Sans Mono:size=10',
    xftalpha = 0.8,

    default_color = 'white',
    color1 = '#00FFFF',  -- Cyan
    color2 = '#FF9900',  -- Orange
    color3 = '#99FF99',  -- Light Green
    color4 = '#FF5555',  -- Red

	lua_load = "scripts/conky_lua_scripts.lua"
};

conky.text = [[
${font JetBrainsMono Nerd Font Mono:size=22}${color1}${time %H:%M:%S}
${font LXGW WenKai:size=12}${color}${time %A, %d %B %Y}${color}${font JetBrainsMono Nerd Font Mono:size=10}
${texeci 1800 curl wttr.in/$(curl -s http://ip-api.com/json | jq -r '.city')_0tpq.png | convert - -transparent black /tmp/weather.png}${image /tmp/weather.png -p 150,-30}
${color2}SYSTEM ${hr 2}${color}
Hostname: ${color}$nodename
Uptime:   ${color}$uptime
Kernel:   ${color}$kernel
${color2}CPU ${hr 2}${color}
Usage: ${color}${lua format %2d ${cpu}}%  [${execi 5 sensors | grep 'Package' | cut -d ':' -f2 | cut -d '+' -f2 | cut -d ' ' -f1}]
${color}Cores: ${color1}${cpugraph -t -l}
${color2}Memory ${hr 2}${color}
RAM:   ${membar  8,100} ${color}${lua format %8s ${mem}} / ${lua format %-8s ${memmax}} (${lua format %2d ${memperc}}%)
Swap:  ${swapbar 8,100} ${color}${lua format %8s ${swap}} / ${lua format %-8s ${swapmax}} (${lua format %2d ${swapperc}}%)
${color2}DISK ${hr 2}${color}
Root:  ${fs_bar 8,100 /} ${color}${lua format %7s ${fs_used /}} / ${lua format %7s ${fs_size /}} (${lua format %2d ${fs_used_perc /}}%)
Home:  ${fs_bar 8,100 /home} ${color}${lua format %7s ${fs_used /home}} / ${lua format %7s ${fs_size /home}} (${lua format %2d ${fs_used_perc /home}}%)
${color2}NETWORK ${hr 2}${color}
${color2}IP: ${color}${addr wlp0s20f3} ${alignr}${color2}WLAN: ${color}${wireless_essid wlp0s20f3}(${wireless_link_qual_perc wlp0s20f3}%)
Down: ${lua format %12s ${downspeed wlp0s20f3}/s} ${alignr}Up: ${lua format %12s ${upspeed wlp0s20f3}/s}
${downspeedgraph wlp0s20f3 20,150 -t -l} ${alignr}${upspeedgraph wlp0s20f3 20,150 -t -l}
${color2}PROCESSES ${hr 2}${color}
Total: ${color}$processes  ${alignr}Running: ${color}$running_processes

Top CPU:
${color2}${top name 1} ${alignr}${top cpu 1}%
${color3}${top name 2} ${alignr}${top cpu 2}%
${color}${top name 3} ${alignr}${top cpu 3}%

Top MEM:
${color2}${top_mem name 1} ${alignr}${top_mem mem_res 1}${top_mem mem 1}%
${color3}${top_mem name 2} ${alignr}${top_mem mem_res 2}${top_mem mem 2}%
${color}${top_mem name 3} ${alignr}${top_mem mem_res 3}${top_mem mem 3}%

${color2}PLAN ${hr 2}${color}${font LXGW WenKai:size=12}
${execi 5 grep '^\*' $HOME/.note | awk '{
	line = substr($0, 3)
	if (substr(line, 1, 1) != "=") {
		count++
		printf "%d.%s\n", count, line
	}else{
		count = 0
		print line
	}
}'}
]];
