conky.config = {
    background = true,
    update_interval = 1,
    double_buffer = true,
    no_buffers = true,
    text_buffer_size = 2048,
    imlib_cache_size = 0,

	minimum_width= 400,

    own_window = true,
    own_window_type = 'override',
    own_window_transparent = false,
    own_window_argb_visual = true,
    own_window_argb_value = 120,
    own_window_hints = 'undecorated,below,sticky,skip_taskbar,skip_pager',

    alignment = 'top_right',
    gap_x = 20,
    gap_y = 50,

    draw_shades = false,
    draw_outline = false,
    draw_borders = false,
    draw_graph_borders = true,
    show_graph_range = false,
    show_graph_scale = true,


    use_xft = true,
    font = 'JetBrainsMono Nerd Font Mono:size=16',
    xftalpha = 0.8,

    default_color = 'white',
    color1 = '#00FFFF',  -- Cyan
    color2 = '#FF9900',  -- Orange
    color3 = '#99FF99',  -- Light Green
    color4 = '#FF5555',  -- Red

    lua_load = "scripts/conky_lua_scripts.lua"
};


package.path = package.path ..";" .. os.getenv("HOME") .. "/.config/conky/scripts/?.lua"
require('net')


conky.text = [[
${font JetBrainsMono Nerd Font Mono:size=36}${color1}${time %H:%M:%S}
${font Noto Sans CJK SC:size=14}${color}${time %A, %d %B %Y}

${font JetBrainsMono Nerd Font Mono:size=14}${color2}PERFORMANCE${hr 2}${color}
CPU: ${cpu}% ${alignr}Mem: ${mem}/${memmax}
${color1}${cpugraph 60,195}${alignr}${memgraph 60,195}

]]

conky.text=conky.text.."${color2}Traffic ${hr 2}\n"
conky.text=conky.text.."IP: ${color}${addr "..iface().."} ${color2} ${alignr}WLAN: ${color}${wireless_essid "..iface().."}(${wireless_link_qual_perc "..iface().."}%)${color2}\n"
conky.text=conky.text.."${color1} ${downspeed "..iface().."}/s${alignr}${upspeed "..iface().."}/s \n"
conky.text = conky.text.."${font JetBrainsMono Nerd Font Mono:size=11}${downspeedgraph "..iface().." 80,195}${alignr}".."${upspeedgraph "..iface().." 80,195}\n"

conky.text=conky.text..[[${font JetBrainsMono Nerd Font Mono:size=14}
${color2}PROCESSES ${hr 2}${color}
Total: ${color}$processes  ${alignr}Running: ${color}$running_processes

Top CPU:
${color2}${top name 1} ${top cpu 1}%${alignr} ${top mem_res 1}
${color3}${top name 2} ${top cpu 2}%${alignr} ${top mem_res 2}
${color}${top name 3} ${top cpu 3}%${alignr} ${top mem_res 3}
${top name 4} ${top cpu 4}%${alignr} ${top mem_res 4}
${top name 5} ${top cpu 5}%${alignr} ${top mem_res 5}

Top MEM:
${color2}${top_mem name 1} ${alignr}${top_mem mem_res 1}${top_mem cpu 1}%
${color3}${top_mem name 2} ${alignr}${top_mem mem_res 2}${top_mem cpu 2}%
${color}${top_mem name 3} ${alignr}${top_mem mem_res 3}${top_mem cpu 3}%
${top_mem name 4} ${alignr}${top_mem mem_res 4}${top_mem cpu 4}%
${top_mem name 5} ${alignr}${top_mem mem_res 5}${top_mem cpu 5}%
]]
