# This is a demo of a wallpaper configuration file
# If you want this configuration file to take effect, delete the _demo suffix in the file name, and the configuration will take effect
#
# wallpaperKeyMap Similarly, the keymap file is the keyboard mapping used when using the video live wallpaper, which is the keyboard configuration of mpv
#


# Configurations
#
# If you want configurations in other formats, you can modify the `getConfig` in `wallpaper.sh` by yourself

# Whether to change the wallpaper randomly at regular intervals 0/1
random = 0

# video / image
random_type = video

# images path
random_image_dir = ~/Desktop/Wallpapers/images/new/

# videos path
random_video_dir = ~/Desktop/Wallpapers/videos/common/

# mpv keymap conf
video_keymap_conf = ~/.config/dwm/wallpaperKeyMap.conf

# Change the interval of wallpaper
duration = 15

# Change the depth of wallpaper
random_depth = 2
